name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/1705alwwwan/hangman
  KUBECONFIG: /home/alwan/.kube/config

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Verify Kubernetes Connection
        env:
          KUBECONFIG: /home/alwan/.kube/config
        run: |
          echo "Current Context:"
          kubectl config current-context

          echo ""
          echo "Cluster Info:"
          kubectl cluster-info

          echo ""
          echo "Nodes:"
          kubectl get nodes

      - name: Apply Kubernetes Manifest
        env:
          KUBECONFIG: /home/alwan/.kube/config
        run: |
          kubectl apply -f k3s/

      - name: Update Deployment Image
        env:
          KUBECONFIG: /home/alwan/.kube/config
        run: |
          kubectl set image deployment/hangman \
          hangman=${{ env.IMAGE_NAME }}:${{ github.sha }} \
          -n hangman

      - name: Wait Rollout
        env:
          KUBECONFIG: /home/alwan/.kube/config
        run: |
          kubectl rollout status deployment/hangman -n hangman

      - name: Show Pods
        env:
          KUBECONFIG: /home/alwan/.kube/config
        run: |
          kubectl get pods -n hangman -o wide

      - name: Show Service
        env:
          KUBECONFIG: /home/alwan/.kube/config
        run: |
          kubectl get svc -n hangman

      - name: Show Ingress
        env:
          KUBECONFIG: /home/alwan/.kube/config
        run: |
          kubectl get ingress -n hangman
