name: Deploy

on:

  workflow_run:

    workflows:

      - CI

    types:

      - completed

jobs:

  deploy:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Apply Manifest
        run: |
          kubectl apply -f k3s/

      - name: Update Image
        run: |
          kubectl set image deployment/hangman \
          hangman=ghcr.io/${{ github.repository }}/hangman:latest \
          -n hangman

      - name: Wait Rollout
        run: |
          kubectl rollout status deployment hangman -n hangman
